# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_real_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='real_type',
        ),
    ]
